/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function RustAKModelFinal({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rustAKModelFinal.glb')
  useFrame((state, delta) => (group.current.rotation.y += 0.01))

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.ak47_lods__1__stock} />
          <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.ak47_lods__1__body} />
          <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.ak47_lods__1__barrel} />
          <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.ak47_lods__1__mag_grip} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rustAKModelFinal.glb')
